#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Translate Bible pericope titles from English to Romanian
"""

import json
import os
import sys

# Set UTF-8 encoding for console output
if sys.platform == 'win32':
    import codecs
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')

# Translation dictionary for Bible pericope titles
# Following Orthodox Romanian Bible terminology
TRANSLATIONS = {
    # Genesis
    "Six Days of Creation and the Sabbath": "Șase zile ale Facerii și Sabatul",
    "Another Account of the Creation": "O altă relatare a Facerii",
    "The First Sin and Its Punishment": "Primul păcat și pedeapsa lui",
    "Cain Murders Abel": "Cain îl ucide pe Abel",
    "Beginnings of Civilization": "Începuturile civilizației",
    "Adam's Descendants to Noah and His Sons": "Urmașii lui Adam până la Noe și fiii săi",
    "The Wickedness of Humankind": "Răutatea omenirii",
    "Noah Pleases God": "Noe Îl mulțumește pe Dumnezeu",
    "The Great Flood": "Marele Potop",
    "The Flood Subsides": "Potopul se potolește",
    "God's Promise to Noah": "Făgăduința lui Dumnezeu către Noe",
    "The Covenant with Noah": "Legământul cu Noe",
    "Noah and His Sons": "Noe și fiii săi",
    "Nations Descended from Noah": "Neamurile coborâte din Noe",
    "The Tower of Babel": "Turnul Babel",
    "Descendants of Shem": "Urmașii lui Sem",
    "Descendants of Terah": "Urmașii lui Tara",
    "The Call of Abram": "Chemarea lui Avram",
    "Abram and Sarai in Egypt": "Avram și Sarai în Egipt",
    "Abram and Lot Separate": "Avram și Lot se despart",
    "Lot's Captivity and Rescue": "Captivitatea și eliberarea lui Lot",
    "Abram Blessed by Melchizedek": "Avram binecuvântat de Melchisedec",
    "God's Covenant with Abram": "Legământul lui Dumnezeu cu Avram",
    "The Birth of Ishmael": "Nașterea lui Ismael",
    "The Sign of the Covenant": "Semnul Legământului",
    "A Son Promised to Abraham and Sarah": "Un fiu făgăduit lui Avraam și Sara",
    "Judgment Pronounced on Sodom": "Judecata rostită asupra Sodomei",
    "The Depravity of Sodom": "Desfrânarea Sodomei",
    "Sodom and Gomorrah Destroyed": "Sodoma și Gomora distruse",
    "The Shameful Origin of Moab and Ammon": "Originea rușinoasă a lui Moab și Amon",
    "Abraham and Sarah at Gerar": "Avraam și Sara în Gherar",
    "The Birth of Isaac": "Nașterea lui Isaac",
    "Hagar and Ishmael Sent Away": "Agar și Ismael alungați",
    "Abraham and Abimelech Make a Covenant": "Avraam și Abimelec fac un legământ",
    "The Command to Sacrifice Isaac": "Porunca de a-L jertfi pe Isaac",
    "The Children of Nahor": "Fiii lui Nahor",
    "Sarah's Death and Burial": "Moartea și înmormântarea Sarei",
    "The Marriage of Isaac and Rebekah": "Căsătoria lui Isaac cu Rebeca",
    "Abraham Marries Keturah": "Avraam se căsătorește cu Chetura",
    "The Death of Abraham": "Moartea lui Avraam",
    "Ishmael's Descendants": "Urmașii lui Ismael",
    "The Birth and Youth of Esau and Jacob": "Nașterea și tinerețea lui Esau și Iacov",
    "Esau Sells His Birthright": "Esau își vinde dreptul de întâi-născut",
    "Isaac and Abimelech": "Isaac și Abimelec",
    "Esau's Hittite Wives": "Soțiile hetite ale lui Esau",
    "Isaac Blesses Jacob": "Isaac îl binecuvântează pe Iacov",
    "Esau's Lost Blessing": "Binecuvântarea pierdută a lui Esau",
    "Jacob Escapes Esau's Fury": "Iacov scapă de furia lui Esau",
    "Esau Marries Ishmael's Daughter": "Esau se căsătorește cu fiica lui Ismael",
    "Jacob's Dream at Bethel": "Visul lui Iacov la Betel",
    "Jacob Meets Rachel": "Iacov o întâlnește pe Rahela",
    "Jacob Marries Laban's Daughters": "Iacov se căsătorește cu fiicele lui Laban",
    "Jacob Prospers at Laban's Expense": "Iacov prosperă pe seama lui Laban",
    "Jacob Flees with Family and Flocks": "Iacov fuge cu familia și turmele",
    "Laban Overtakes Jacob": "Laban îl ajunge pe Iacov",
    "Laban and Jacob Make a Covenant": "Laban și Iacov fac un legământ",
    "Jacob Sends Presents to Appease Esau": "Iacov trimite daruri pentru a-l potoli pe Esau",
    "Jacob Wrestles at Peniel": "Iacov se luptă la Peniel",
    "Jacob and Esau Meet": "Iacov și Esau se întâlnesc",
    "Jacob Reaches Shechem": "Iacov ajunge la Sihem",
    "The Rape of Dinah": "Violarea Dinei",
    "Dinah's Brothers Avenge Their Sister": "Frații Dinei își răzbună sora",
    "Jacob Returns to Bethel": "Iacov se întoarce la Betel",
    "The Birth of Benjamin and the Death of Rachel": "Nașterea lui Beniamin și moartea Rahelei",
    "The Death of Isaac": "Moartea lui Isaac",
    "Esau's Descendants": "Urmașii lui Esau",
    "Clans and Kings of Edom": "Clanurile și regii Edomului",
    "Joseph Dreams of Greatness": "Iosif visează mărire",
    "Joseph Is Sold by His Brothers": "Iosif este vândut de frații săi",
    "Judah and Tamar": "Iuda și Tamar",
    "Joseph and Potiphar's Wife": "Iosif și soția lui Potifar",
    "The Dreams of Two Prisoners": "Visele celor doi prizonieri",
    "Joseph Interprets Pharaoh's Dream": "Iosif tâlcuiește visul Faraonului",
    "Joseph's Rise to Power": "Înălțarea lui Iosif la putere",
    "Joseph's Brothers Go to Egypt": "Frații lui Iosif merg în Egipt",
    "Joseph's Brothers Return to Canaan": "Frații lui Iosif se întorc în Canaan",
    "The Brothers Come Again, Bringing Benjamin": "Frații vin din nou, aducându-l pe Beniamin",
    "Joseph Detains Benjamin": "Iosif îl reține pe Beniamin",
    "Judah Pleads for Benjamin's Release": "Iuda pledează pentru eliberarea lui Beniamin",
    "Joseph Reveals Himself to His Brothers": "Iosif se dezvăluie fraților săi",
    "Jacob Brings His Whole Family to Egypt": "Iacov își aduce toată familia în Egipt",
    "Jacob Settles in Goshen": "Iacov se așază în Gosen",
    "The Famine in Egypt": "Foametea în Egipt",
    "The Last Days of Jacob": "Ultimele zile ale lui Iacov",
    "Jacob Blesses Joseph's Sons": "Iacov îi binecuvântează pe fiii lui Iosif",
    "Jacob's Last Words to His Sons": "Ultimele cuvinte ale lui Iacov către fiii săi",
    "Jacob's Death and Burial": "Moartea și înmormântarea lui Iacov",
    "Joseph Forgives His Brothers": "Iosif îi iartă pe frații săi",
    "Joseph's Last Days and Death": "Ultimele zile și moartea lui Iosif",

    # Exodus
    "The Israelites Are Oppressed": "Israeliții sunt asuприți",
    "Birth and Youth of Moses": "Nașterea și tinerețea lui Moise",
    "Moses Flees to Midian": "Moise fuge în Madian",
    "Moses at the Burning Bush": "Moise la rugul aprins",
    "The Divine Name Revealed": "Numele dumnezeiesc descoperit",
    "Moses' Miraculous Power": "Puterea minunată a lui Moise",
    "Moses Returns to Egypt": "Moise se întoarce în Egipt",
    "Bricks without Straw": "Cărămizi fără paie",
    "Israel's Deliverance Assured": "Izbăvirea lui Israel asigurată",
    "The Genealogy of Moses and Aaron": "Genealogia lui Moise și Aaron",
    "Moses and Aaron Obey God's Commands": "Moise și Aaron ascultă poruncile lui Dumnezeu",
    "Aaron's Miraculous Rod": "Toiagul minunat al lui Aaron",
    "The First Plague Water Turned to Blood": "Prima urgie: apa prefăcută în sânge",
    "The Second Plague Frogs": "A doua urgie: broaștele",
    "The Third Plague Gnats": "A treia urgie: țânțarii",
    "The Fourth Plague Flies": "A patra urgie: muștele",
    "The Fifth Plague Livestock Diseased": "A cincea urgie: boala vitelor",
    "The Sixth Plague Boils": "A șasea urgie: bubele",
    "The Seventh Plague Thunder and Hail": "A șaptea urgie: tunetul și grindina",
    "The Eighth Plague Locusts": "A opta urgie: lăcustele",
    "The Ninth Plague Darkness": "A noua urgie: întunericul",
    "Warning of the Final Plague": "Avertizarea despre urgia finală",
    "The First Passover Instituted": "Instituirea primei Paști",
    "The Tenth Plague Death of the Firstborn": "A zecea urgie: moartea întâilor-născuți",
    "The Exodus From Rameses to Succoth": "Ieșirea din Ramses la Sucot",
    "Directions for the Passover": "Indicații pentru Paști",
    "The Festival of Unleavened Bread": "Sărbătoarea azimelor",
    "The Consecration of the Firstborn": "Sfințirea întâilor-născuți",
    "The Pillars of Cloud and Fire": "Stâlpii de nor și de foc",
    "Crossing the Red Sea": "Trecerea Mării Roșii",
    "The Pursuers Drowned": "Prigonitorii înecați",
    "The Song of Moses": "Cântarea lui Moise",
    "The Song of Miriam": "Cântarea Mariei",
    "Bitter Water Made Sweet": "Apa amară făcută dulce",
    "Bread from Heaven": "Pâine din cer",
    "Water from the Rock": "Apă din stâncă",
    "Amalek Attacks Israel and Is Defeated": "Amalec atacă pe Israel și este învins",
    "Jethro's Advice": "Sfatul lui Ietro",
    "The Israelites Reach Mount Sinai": "Israeliții ajung la Muntele Sinai",
    "The People Consecrated": "Poporul sfințit",
    "The Ten Commandments": "Cele zece porunci",
    "The Law concerning the Altar": "Legea despre altar",
    "The Law concerning Slaves": "Legea despre robi",
    "The Law concerning Violence": "Legea despre violență",
    "Laws concerning Property": "Legile despre proprietate",
    "Laws of Restitution": "Legile restituirii",
    "Social and Religious Laws": "Legi sociale și religioase",
    "Justice for All": "Dreptate pentru toți",
    "Sabbatical Year and Sabbath": "Anul sabatic și Sabatul",
    "The Annual Festivals": "Sărbătorile anuale",
    "The Conquest of Canaan Promised": "Cucerirea Canaanului făgăduită",
    "The Blood of the Covenant": "Sângele Legământului",
    "On the Mountain with God": "Pe munte cu Dumnezeu",
    "Offerings for the Tabernacle": "Daruri pentru Cort",
    "The Ark of the Covenant": "Chivotul Legământului",
    "The Table for the Bread of the Presence": "Masa pentru pâinile punerii înainte",
    "The Lampstand": "Sfeșnicul",
    "The Tabernacle": "Cortul",
    "The Framework": "Structura",
    "The Curtain": "Perdeaua",
    "The Altar of Burnt Offering": "Altarul arderilor de tot",
    "The Court and Its Hangings": "Curtea și perdelele ei",
    "The Oil for the Lamp": "Untdelemnul pentru candelă",
    "Vestments for the Priesthood": "Veșmintele preoției",
    "The Ephod": "Efodul",
    "The Breastplate": "Pieptarul",
    "Other Priestly Vestments": "Alte veșminte preoțești",
    "The Ordination of the Priests": "Hirotonirea preoților",
    "The Daily Offerings": "Jertfele zilnice",
    "The Altar of Incense": "Altarul tămâierii",
    "The Half Shekel for the Sanctuary": "Jumătate de siclu pentru Sfântul Locaș",
    "The Bronze Basin": "Ligheanul de aramă",
    "The Anointing Oil and Incense": "Untdelemnul ungerii și tămâia",
    "Bezalel and Oholiab": "Bețaleel și Ooliav",
    "The Sabbath Law": "Legea Sabatului",
    "The Two Tablets of the Covenant": "Cele două table ale Legământului",
    "The Golden Calf": "Vițelul de aur",
    "The Command to Leave Sinai": "Porunca de a părăsi Sinai",
    "The Tent outside the Camp": "Cortul în afara taberei",
    "Moses' Intercession": "Mijlocirea lui Moise",
    "Moses Makes New Tablets": "Moise face table noi",
    "The Covenant Renewed": "Legământul reînnoit",
    "The Shining Face of Moses": "Fața strălucitoare a lui Moise",
    "Sabbath Regulations": "Rânduielile Sabatului",
    "Preparations for Making the Tabernacle": "Pregătiri pentru facerea Cortului",
    "Construction of the Tabernacle": "Construirea Cortului",
    "Making the Ark of the Covenant": "Facerea Chivotului Legământului",
    "Making the Table for the Bread of the Presence": "Facerea mesei pentru pâinile punerii înainte",
    "Making the Lampstand": "Facerea sfeșnicului",
    "Making the Altar of Incense": "Facerea altarului tămâierii",
    "Making the Anointing Oil and the Incense": "Facerea untdelemnului ungerii și a tămâiei",
    "Making the Altar of Burnt Offering": "Facerea altarului arderilor de tot",
    "Making the Court of the Tabernacle": "Facerea curții Cortului",
    "Materials of the Tabernacle": "Materialele Cortului",
    "Making the Vestments for the Priesthood": "Facerea veșmintelor preoției",
    "The Work Completed": "Lucrarea încheiată",
    "The Tabernacle Erected and Its Equipment Installed": "Cortul ridicat și uneltele lui așezate",
    "The Cloud and the Glory": "Norul și slava",

    # Leviticus
    "The Burnt Offering": "Arderea de tot",
    "Grain Offerings": "Darurile de mâncare",
    "Offerings of Well-Being": "Jertfele de pace",
    "Sin Offerings": "Jertfele pentru păcat",
    "Offerings with Restitution": "Jertfele cu restituire",
    "Instructions concerning Sacrifices": "Învățături despre jertfe",
    "Further Instructions": "Învățături suplimentare",
    "The Rites of Ordination": "Rânduielile hirotoniei",
    "Aaron's Priesthood Inaugurated": "Preoția lui Aaron inaugurată",
    "Nadab and Abihu": "Nadab și Abihu",
    "Clean and Unclean Foods": "Mâncări curate și necurate",
    "Unclean Animals": "Animale necurate",
    "Purification of Women after Childbirth": "Curățirea femeilor după naștere",
    "Leprosy, Varieties and Symptoms": "Lepra, varietăți și simptome",
    "Purification of Lepers and Leprous Houses": "Curățirea leproșilor și caselor leproase",
    "Concerning Bodily Discharges": "Despre scurgerile trupești",
    "The Day of Atonement": "Ziua Ispășirii",
    "The Slaughtering of Animals": "Înjunghierea animalelor",
    "Eating Blood Prohibited": "Mâncarea sângelui oprită",
    "Sexual Relations": "Relații sexuale",
    "Ritual and Moral Holiness": "Sfințenie rituală și morală",
    "Penalties for Violations of Holiness": "Pedepse pentru încălcările sfințeniei",
    "The Holiness of Priests": "Sfințenia preoților",
    "The Use of Holy Offerings": "Folosirea darurilor sfinte",
    "Acceptable Offerings": "Daruri primite",
    "Appointed Festivals": "Sărbători rânduite",
    "The Sabbath, Passover, and Unleavened Bread": "Sabatul, Paștile și azimele",
    "The Offering of First Fruits": "Darul primelor roade",
    "The Festival of Weeks": "Sărbătoarea Săptămânilor",
    "The Festival of Trumpets": "Sărbătoarea trâmbițelor",
    "The Festival of Booths": "Sărbătoarea Corturilor",
    "The Lamp": "Candela",
    "The Bread for the Tabernacle": "Pâinea pentru Cort",
    "Blasphemy and Its Punishment": "Hulirea și pedeapsa ei",
    "The Sabbatical Year": "Anul sabatic",
    "The Year of Jubilee": "Anul de veselie",
    "Redemption of Property": "Răscumpărarea proprietății",
    "Lending to the Poor": "Împrumutul săracilor",
    "Rewards for Obedience": "Răsplăți pentru ascultare",
    "Penalties for Disobedience": "Pedepse pentru neascultare",
    "Votive Offerings": "Daruri făgăduite",

    # Numbers
    "The First Census of Israel": "Prima recensământare a lui Israel",
    "The Order of Encampment and Marching": "Rânduiala taberei și a mersului",
    "The Sons of Aaron": "Fiii lui Aaron",
    "The Duties of the Levites": "Datoriile leviților",
    "A Census of the Levites": "Recensământarea leviților",
    "The Kohathites": "Chehatiții",
    "The Gershonites and Merarites": "Gherșoniții și meraritii",
    "Unclean Persons": "Persoane necurate",
    "Confession and Restitution": "Mărturisire și restituire",
    "Concerning an Unfaithful Wife": "Despre o soție necredincioasă",
    "The Nazirites": "Nazireii",
    "The Priestly Benediction": "Binecuvântarea preoțească",
    "Offerings of the Leaders": "Darurile căpeteniilor",
    "The Seven Lamps": "Cele șapte candele",
    "Consecration and Service of the Levites": "Sfințirea și slujirea leviților",
    "The Passover at Sinai": "Paștile la Sinai",
    "The Passover Reviewed": "Paștile revăzute",
    "The Cloud and the Fire": "Norul și focul",
    "The Silver Trumpets": "Trâmbițele de argint",
    "Departure from Sinai": "Plecarea de la Sinai",
    "Complaining in the Desert": "Cârtire în pustie",
    "The Seventy Elders": "Cei șaptezeci de bătrâni",
    "The Quails": "Prepelițele",
    "Aaron and Miriam Jealous of Moses": "Aaron și Maria geloși pe Moise",
    "Spies Sent into Canaan": "Iscoade trimise în Canaan",
    "The Report of the Spies": "Raportul iscoazilor",
    "The People Rebel": "Poporul se răscoală",
    "An Attempted Invasion is Repulsed": "O tentativă de invazie este respinsă",
    "Various Offerings": "Daruri felurite",
    "Penalty for Violating the Sabbath": "Pedeapsa pentru încălcarea Sabatului",
    "Fringes on Garments": "Ciucuri pe veșminte",
    "Revolt of Korah, Dathan, and Abiram": "Răscoala lui Core, Datan și Abiram",
    "The Budding of Aaron's Rod": "Înflorirea toiagului lui Aaron",
    "Responsibility of Priests and Levites": "Răspunderea preoților și leviților",
    "Ceremony of the Red Heifer": "Ceremonia vacii roșii",
    "The Waters of Meribah": "Apele Meriba",
    "Passage through Edom Refused": "Trecerea prin Edom refuzată",
    "The Death of Aaron": "Moartea lui Aaron",
    "The Bronze Serpent": "Șarpele de aramă",
    "The Journey to Moab": "Călătoria spre Moab",
    "King Sihon Defeated": "Regele Sihon învins",
    "King Og Defeated": "Regele Og învins",
    "Defeat of King Sihon": "Înfrângerea regelui Sihon",
    "Defeat of King Og": "Înfrângerea regelui Og",
    "Balak Summons Balaam to Curse Israel": "Balac îl cheamă pe Balaam să blesteme pe Israel",
    "Balaam, the Donkey, and the Angel": "Balaam, măgărița și îngerul",
    "Balaam's First Oracle": "Primul oracle al lui Balaam",
    "Balaam's Second Oracle": "Al doilea oracle al lui Balaam",
    "Balaam's Third Oracle": "Al treilea oracle al lui Balaam",
    "Balaam's Fourth Oracle": "Al patrulea oracle al lui Balaam",
    "Worship of Baal of Peor": "Închinarea la Baal-Peor",
    "A Census of the New Generation": "Recensământarea noii generații",
    "The Daughters of Zelophehad": "Fiicele lui Țelofhad",
    "Joshua Appointed Moses' Successor": "Iosua numit urmașul lui Moise",
    "Daily Offerings": "Jertfe zilnice",
    "Sabbath Offerings": "Jertfe de Sabat",
    "Monthly Offerings": "Jertfe lunare",
    "Offerings at Passover": "Jertfe la Paști",
    "Offerings at the Festival of Weeks": "Jertfe la Sărbătoarea Săptămânilor",
    "The Festival of Weeks Reviewed": "Sărbătoarea Săptămânilor revăzută",
    "Offerings at the Festival of Trumpets": "Jertfe la Sărbătoarea trâmbițelor",
    "Offerings on the Day of Atonement": "Jertfe în Ziua Ispășirii",
    "Offerings at the Festival of Booths": "Jertfe la Sărbătoarea Corturilor",
    "The Festival of Booths Reviewed": "Sărbătoarea Corturilor revăzută",
    "Vows Made by Women": "Juruințe făcute de femei",
    "War against Midian": "Război împotriva Madianului",
    "Return from the War": "Întoarcerea de la război",
    "Disposition of Captives and Booty": "Împărțirea captivilor și prăzii",
    "Conquest and Division of Transjordan": "Cucerirea și împărțirea Transiordaniei",
    "The Stages of Israel's Journey from Egypt": "Etapele călătoriei lui Israel din Egipt",
    "Directions for the Conquest of Canaan": "Indicații pentru cucerirea Canaanului",
    "The Boundaries of the Land": "Hotarele țării",
    "Tribal Leaders": "Căpeteniile triburilor",
    "Cities for the Levites": "Cetăți pentru leviți",
    "Cities of Refuge": "Cetăți de scăpare",
    "Cities of Refuge East of the Jordan": "Cetăți de scăpare la răsărit de Iordan",
    "Concerning Murder and Blood Revenge": "Despre ucidere și răzbunarea sângelui",
    "Marriage of Female Heirs": "Căsătoria moștenitoarelor",

    # Deuteronomy
    "Events at Horeb Recalled": "Întâmplările de la Horeb amintite",
    "The Command to Leave Horeb": "Porunca de a părăsi Horeb",
    "Appointment of Tribal Leaders": "Numirea căpeteniilor triburilor",
    "Israel's Refusal to Enter the Land": "Refuzul lui Israel de a intra în țară",
    "The Penalty for Israel's Rebellion": "Pedeapsa pentru răzvrătirea lui Israel",
    "The Desert Years": "Anii pustiei",
    "Transition to the Second Address": "Trecerea la a doua cuvântare",
    "Moses Views Canaan from Pisgah": "Moise vede Canaanul din Pisga",
    "Moses Commands Obedience": "Moise poruncește ascultare",
    "Moses the Mediator of God's Will": "Moise mijlocitorul voii lui Dumnezeu",
    "The Great Commandment": "Marea poruncă",
    "Caution against Disobedience": "Prevenire împotriva neascultării",
    "A Chosen People": "Un popor ales",
    "Blessings for Obedience": "Binecuvântări pentru ascultare",
    "A Warning Not to Forget God in Prosperity": "Avertizare să nu-L uite pe Dumnezeu în prosperitate",
    "The Consequences of Rebelling against God": "Urmările răzvrătirii împotriva lui Dumnezeu",
    "Moses Intercedes for the People": "Moise mijlocește pentru popor",
    "The Second Pair of Tablets": "A doua pereche de table",
    "The Essence of the Law": "Esența Legii",
    "God's Fidelity Assured": "Credincioșia lui Dumnezeu asigurată",
    "The Blessing and the Curse": "Binecuvântarea și blestemul",
    "Pagan Shrines to Be Destroyed": "Locașurile păgâne să fie distruse",
    "A Prescribed Place of Worship": "Un loc rânduit de închinare",
    "Pagan Practices Forbidden": "Practicile păgâne oprite",
    "Warning against Idolatry": "Avertizare împotriva idolatriei",
    "Deuteronomy Chapter 13": "Deuteronomul capitolul 13",
    "Regulations concerning Tithes": "Rânduieli despre zeciuieli",
    "Laws concerning the Sabbatical Year": "Legi despre anul sabatic",
    "The Firstborn of Livestock": "Întâii-născuți din vite",
    "The Festival of Passover": "Sărbătoarea Paștilor",
    "Municipal Judges and Officers": "Judecători și dregători municipali",
    "Forbidden Forms of Worship": "Forme oprite de închinare",
    "Legal Decisions by Priests and Judges": "Hotărâri legale de preoți și judecători",
    "Limitations of Royal Authority": "Limitări ale autorității regale",
    "Privileges of Priests and Levites": "Privilegii ale preoților și leviților",
    "The Priests' Portion": "Partea preoților",
    "Child-Sacrifice, Divination, and Magic Prohibited": "Jertfirea copiilor, ghicitul și vrăjitoria oprite",
    "A New Prophet Like Moses": "Un nou profet ca Moise",
    "Laws concerning the Cities of Refuge": "Legi despre cetățile de scăpare",
    "Property Boundaries": "Hotarele proprietății",
    "Law concerning Witnesses": "Legea despre martori",
    "Rules of Warfare": "Rânduieli de război",
    "Law concerning Murder by Persons Unknown": "Legea despre ucidere de către persoane necunoscute",
    "Female Captives": "Captive",
    "The Right of the Firstborn": "Dreptul întâiului-născut",
    "Rebellious Children": "Copii răzvrătiți",
    "Miscellaneous Laws": "Legi felurite",
    "Laws concerning Sexual Relations": "Legi despre relații sexuale",
    "Those Excluded from the Assembly": "Cei excluși din adunare",
    "Sanitary, Ritual, and Humanitarian Precepts": "Precepte sanitare, rituale și umanitare",
    "Laws concerning Marriage and Divorce": "Legi despre căsătorie și divorț",
    "Levirate Marriage": "Căsătoria leviratului",
    "Various Commands": "Porunci felurite",
    "First Fruits and Tithes": "Primele roade și zeciuielile",
    "Concluding Exhortation": "Îndemnul de încheiere",
    "The Inscribed Stones and Altar on Mount Ebal": "Pietrele inscripționate și altarul pe Muntele Ebal",
    "Twelve Curses": "Douăsprezece blesteme",
    "Warnings against Disobedience": "Avertizări împotriva neascultării",
    "The Covenant Renewed in Moab": "Legământul reînnoit în Moab",
    "Exhortation to Choose Life": "Îndemn să aleagă viața",
    "Joshua Becomes Moses' Successor": "Iosua devine urmașul lui Moise",
    "The Law to Be Read Every Seventh Year": "Legea să fie citită în fiecare al șaptelea an",
    "Moses and Joshua Receive God's Charge": "Moise și Iosua primesc însărcinarea lui Dumnezeu",
    "Moses' Death Foretold": "Moartea lui Moise prevestită",
    "Moses' Final Blessing on Israel": "Binecuvântarea finală a lui Moise pentru Israel",
    "Moses Dies and Is Buried in the Land of Moab": "Moise moare și este îngropat în țara Moabului",
    "The Redemption of the Firstborn": "Răscumpărarea întâilor-născuți",

    # Titles with curly apostrophes (U+2019)
    "Adam's Descendants to Noah and His Sons": "Urmașii lui Adam până la Noe și fiii săi",
    "God's Promise to Noah": "Făgăduința lui Dumnezeu către Noe",
    "Lot's Captivity and Rescue": "Captivitatea și eliberarea lui Lot",
    "God's Covenant with Abram": "Legământul lui Dumnezeu cu Avram",
    "Sarah's Death and Burial": "Moartea și înmormântarea Sarei",
    "Ishmael's Descendants": "Urmașii lui Ismael",
    "Esau's Hittite Wives": "Soțiile hetite ale lui Esau",
    "Esau's Lost Blessing": "Binecuvântarea pierdută a lui Esau",
    "Esau Marries Ishmael's Daughter": "Esau se căsătorește cu fiica lui Ismael",
    "Jacob's Dream at Bethel": "Visul lui Iacov la Betel",
    "Jacob Marries Laban's Daughters": "Iacov se căsătorește cu fiicele lui Laban",
    "Jacob Prospers at Laban's Expense": "Iacov prosperă pe seama lui Laban",
    "Jacob Escapes Esau's Fury": "Iacov scapă de furia lui Esau",
    "Dinah's Brothers Avenge Their Sister": "Frații Dinei își răzbună sora",
    "Esau's Descendants": "Urmașii lui Esau",
    "Joseph and Potiphar's Wife": "Iosif și soția lui Potifar",
    "Joseph Interprets Pharaoh's Dream": "Iosif tâlcuiește visul Faraonului",
    "Joseph's Rise to Power": "Înălțarea lui Iosif la putere",
    "Joseph's Brothers Go to Egypt": "Frații lui Iosif merg în Egipt",
    "Joseph's Brothers Return to Canaan": "Frații lui Iosif se întorc în Canaan",
    "Judah Pleads for Benjamin's Release": "Iuda pledează pentru eliberarea lui Beniamin",
    "Jacob Blesses Joseph's Sons": "Iacov îi binecuvântează pe fiii lui Iosif",
    "Jacob's Last Words to His Sons": "Ultimele cuvinte ale lui Iacov către fiii săi",
    "Jacob's Death and Burial": "Moartea și înmormântarea lui Iacov",
    "Joseph's Last Days and Death": "Ultimele zile și moartea lui Iosif",
    "Moses' Miraculous Power": "Puterea minunată a lui Moise",
    "Israel's Deliverance Assured": "Izbăvirea lui Israel asigurată",
    "Moses and Aaron Obey God's Commands": "Moise și Aaron ascultă poruncile lui Dumnezeu",
    "Aaron's Miraculous Rod": "Toiagul minunat al lui Aaron",
    "Jethro's Advice": "Sfatul lui Ietro",
    "Moses' Intercession": "Mijlocirea lui Moise",
    "Aaron's Priesthood Inaugurated": "Preoția lui Aaron inaugurată",
    "Census of the Levites": "Recensământarea leviților",
    "The Budding of Aaron's Rod": "Înflorirea toiagului lui Aaron",
    "The Priests' Portion": "Partea preoților",
    "Balaam's First Oracle": "Primul oracle al lui Balaam",
    "Balaam's Second Oracle": "Al doilea oracle al lui Balaam",
    "Balaam's Third Oracle": "Al treilea oracle al lui Balaam",
    "Balaam's Fourth Oracle": "Al patrulea oracle al lui Balaam",
    "Joshua Appointed Moses' Successor": "Iosua numit urmașul lui Moise",
    "The Stages of Israel's Journey from Egypt": "Etapele călătoriei lui Israel din Egipt",
    "Israel's Refusal to Enter the Land": "Refuzul lui Israel de a intra în țară",
    "The Penalty for Israel's Rebellion": "Pedeapsa pentru răzvrătirea lui Israel",
    "Moses the Mediator of God's Will": "Moise mijlocitorul voii lui Dumnezeu",
    "God's Fidelity Assured": "Credincioșia lui Dumnezeu asigurată",
    "Joshua Becomes Moses' Successor": "Iosua devine urmașul lui Moise",
    "Moses and Joshua Receive God's Charge": "Moise și Iosua primesc însărcinarea lui Dumnezeu",
    "Moses' Death Foretold": "Moartea lui Moise prevestită",
    "Moses' Final Blessing on Israel": "Binecuvântarea finală a lui Moise pentru Israel",
}

def translate_pericopes(file_path):
    """Translate pericope titles in a JSON file."""
    print(f"\nProcessing: {os.path.basename(file_path)}")

    # Read the JSON file
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Track translations
    translated_count = 0
    not_found = []

    # Translate each pericope
    for pericope in data['pericopes']:
        title_en = pericope['title_en']

        if title_en in TRANSLATIONS:
            pericope['title_ro'] = TRANSLATIONS[title_en]
            translated_count += 1
        else:
            not_found.append(title_en)

    # Write back to file
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"  Translated: {translated_count} titles")

    if not_found:
        print(f"  NOT FOUND: {len(not_found)} titles")
        for title in not_found[:5]:  # Show first 5
            print(f"    - {title}")
        if len(not_found) > 5:
            print(f"    ... and {len(not_found) - 5} more")

    return translated_count, not_found

def main():
    """Main function to process all files."""
    base_path = r"C:\Users\User\Documents\GitHub\orthodox_bible\bible_books_pericopes"

    files = [
        "01_Facerea_pericopes.json",
        "02_Ieșirea_pericopes.json",
        "03_Leviticul_pericopes.json",
        "04_Numerii_pericopes.json",
        "05_Deuteronomul_pericopes.json"
    ]

    total_translated = 0
    all_not_found = []

    for filename in files:
        file_path = os.path.join(base_path, filename)
        count, not_found = translate_pericopes(file_path)
        total_translated += count
        all_not_found.extend(not_found)

    print(f"\n{'='*60}")
    print(f"SUMMARY:")
    print(f"  Total translated: {total_translated}")
    print(f"  Total not found: {len(all_not_found)}")

    if all_not_found:
        print(f"\n  Unique untranslated titles: {len(set(all_not_found))}")

if __name__ == "__main__":
    main()
